/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param iconLight 
 * @param iconDark 
 */


data class AaguidDetails (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "iconLight")
    val iconLight: kotlin.String,

    @Json(name = "iconDark")
    val iconDark: kotlin.String

) {


}

