/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: signupMinusInit,passkeyMinusAppend,phoneMinusVerify,emailMinusVerify,passkeyMinusAppended,completed,socialMinusVerify,loginMinusInit,passkeyMinusVerify,conditionalMinusUiMinusCompleted,postMinusSignupMinusEmailMinusVerify,passkeyMinusAppendMinusAfterMinusHybrid
 */

@JsonClass(generateAdapter = false)
enum class BlockType(val value: kotlin.String) {

    @Json(name = "signup-init")
    signupMinusInit("signup-init"),

    @Json(name = "passkey-append")
    passkeyMinusAppend("passkey-append"),

    @Json(name = "phone-verify")
    phoneMinusVerify("phone-verify"),

    @Json(name = "email-verify")
    emailMinusVerify("email-verify"),

    @Json(name = "passkey-appended")
    passkeyMinusAppended("passkey-appended"),

    @Json(name = "completed")
    completed("completed"),

    @Json(name = "social-verify")
    socialMinusVerify("social-verify"),

    @Json(name = "login-init")
    loginMinusInit("login-init"),

    @Json(name = "passkey-verify")
    passkeyMinusVerify("passkey-verify"),

    @Json(name = "conditional-ui-completed")
    conditionalMinusUiMinusCompleted("conditional-ui-completed"),

    @Json(name = "post-signup-email-verify")
    postMinusSignupMinusEmailMinusVerify("post-signup-email-verify"),

    @Json(name = "passkey-append-after-hybrid")
    passkeyMinusAppendMinusAfterMinusHybrid("passkey-append-after-hybrid");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BlockType) "$data" else null

        /**
         * Returns a valid [BlockType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BlockType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

