/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.AuthType
import com.corbado.api.models.BlockBodyData
import com.corbado.api.models.BlockType
import com.corbado.api.models.ContinueOnOtherDevice
import com.corbado.api.models.RequestError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param block 
 * @param authType 
 * @param `data` 
 * @param alternatives 
 * @param error 
 * @param continueOnOtherDevice 
 */


data class BlockBody (

    @Json(name = "block")
    val block: BlockType,

    @Json(name = "authType")
    val authType: AuthType,

    @Json(name = "data")
    val `data`: BlockBodyData,

    @Json(name = "alternatives")
    val alternatives: kotlin.collections.List<BlockBody>? = null,

    @Json(name = "error")
    val error: RequestError? = null,

    @Json(name = "continueOnOtherDevice")
    val continueOnOtherDevice: ContinueOnOtherDevice? = null

) {


}

