/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ts 
 * @param source 
 */


data class ClientStateMeta (

    @Json(name = "ts")
    val ts: kotlin.Int,

    @Json(name = "source")
    val source: ClientStateMeta.Source

) {

    /**
     * 
     *
     * Values: ls,url,native
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "ls") ls("ls"),
        @Json(name = "url") url("url"),
        @Json(name = "native") native("native");
    }

}

