/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param conditionalCreate 
 * @param conditionalMediation 
 * @param hybridTransport 
 * @param passkeyPlatformAuthenticator 
 * @param userVerifyingPlatformAuthenticator 
 */


data class ClientCapabilities (

    @Json(name = "conditionalCreate")
    val conditionalCreate: kotlin.Boolean? = null,

    @Json(name = "conditionalMediation")
    val conditionalMediation: kotlin.Boolean? = null,

    @Json(name = "hybridTransport")
    val hybridTransport: kotlin.Boolean? = null,

    @Json(name = "passkeyPlatformAuthenticator")
    val passkeyPlatformAuthenticator: kotlin.Boolean? = null,

    @Json(name = "userVerifyingPlatformAuthenticator")
    val userVerifyingPlatformAuthenticator: kotlin.Boolean? = null

) {


}

