/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.ClientCapabilities
import com.corbado.api.models.ClientStateMeta
import com.corbado.api.models.JavaScriptHighEntropy
import com.corbado.api.models.NativeMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bluetoothAvailable 
 * @param clientEnvHandle 
 * @param visitorId 
 * @param canUsePasskeys Deprecated, use isUserVerifyingPlatformAuthenticatorAvailable instead
 * @param isUserVerifyingPlatformAuthenticatorAvailable 
 * @param isConditionalMediationAvailable 
 * @param clientCapabilities 
 * @param javaScriptHighEntropy 
 * @param isNative 
 * @param webdriver 
 * @param privateMode 
 * @param clientEnvHandleMeta 
 * @param nativeMeta 
 */


data class ClientInformation (

    @Json(name = "bluetoothAvailable")
    val bluetoothAvailable: kotlin.Boolean? = null,

    @Json(name = "clientEnvHandle")
    val clientEnvHandle: kotlin.String? = null,

    @Json(name = "visitorId")
    val visitorId: kotlin.String? = null,

    /* Deprecated, use isUserVerifyingPlatformAuthenticatorAvailable instead */
    @Json(name = "canUsePasskeys")
    val canUsePasskeys: kotlin.Boolean? = null,

    @Json(name = "isUserVerifyingPlatformAuthenticatorAvailable")
    val isUserVerifyingPlatformAuthenticatorAvailable: kotlin.Boolean? = null,

    @Json(name = "isConditionalMediationAvailable")
    val isConditionalMediationAvailable: kotlin.Boolean? = null,

    @Json(name = "clientCapabilities")
    val clientCapabilities: ClientCapabilities? = null,

    @Json(name = "javaScriptHighEntropy")
    val javaScriptHighEntropy: JavaScriptHighEntropy? = null,

    @Json(name = "isNative")
    val isNative: kotlin.Boolean? = null,

    @Json(name = "webdriver")
    val webdriver: kotlin.Boolean? = null,

    @Json(name = "privateMode")
    val privateMode: kotlin.Boolean? = null,

    @Json(name = "clientEnvHandleMeta")
    val clientEnvHandleMeta: ClientStateMeta? = null,

    @Json(name = "nativeMeta")
    val nativeMeta: NativeMeta? = null

) {


}

