/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param attestationOptions 
 * @param variant 
 * @param isRestrictedBrowser 
 * @param autoAppend 
 */


data class ConnectAppendStartRsp (

    @Json(name = "attestationOptions")
    val attestationOptions: kotlin.String,

    @Json(name = "variant")
    val variant: ConnectAppendStartRsp.Variant,

    @Json(name = "isRestrictedBrowser")
    val isRestrictedBrowser: kotlin.Boolean,

    @Json(name = "autoAppend")
    val autoAppend: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: default,afterMinusHybrid,afterMinusError
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "default") default("default"),
        @Json(name = "after-hybrid") afterMinusHybrid("after-hybrid"),
        @Json(name = "after-error") afterMinusError("after-error");
    }

}

