/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param expiresAt 
 * @param frontendApiUrl 
 * @param loginAllowed 
 * @param flags 
 * @param newClientEnvHandle 
 * @param conditionalUIChallenge 
 */


data class ConnectLoginInitRsp (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.Int,

    @Json(name = "frontendApiUrl")
    val frontendApiUrl: kotlin.String,

    @Json(name = "loginAllowed")
    val loginAllowed: kotlin.Boolean,

    @Json(name = "flags")
    val flags: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "newClientEnvHandle")
    val newClientEnvHandle: kotlin.String? = null,

    @Json(name = "conditionalUIChallenge")
    val conditionalUIChallenge: kotlin.String? = null

) {


}

