/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.ClientStateMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identifier 
 * @param source 
 * @param loadedMs 
 * @param loginConnectToken 
 * @param identifierHintAvailable 
 * @param oneTapMeta 
 */


data class ConnectLoginStartReq (

    @Json(name = "identifier")
    val identifier: kotlin.String,

    @Json(name = "source")
    val source: ConnectLoginStartReq.Source,

    @Json(name = "loadedMs")
    val loadedMs: kotlin.Long,

    @Json(name = "loginConnectToken")
    val loginConnectToken: kotlin.String? = null,

    @Json(name = "identifierHintAvailable")
    val identifierHintAvailable: kotlin.Boolean? = null,

    @Json(name = "oneTapMeta")
    val oneTapMeta: ClientStateMeta? = null

) {

    /**
     * 
     *
     * Values: oneMinusTap,textMinusField,errorMinusSoft,errorMinusHard
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "one-tap") oneMinusTap("one-tap"),
        @Json(name = "text-field") textMinusField("text-field"),
        @Json(name = "error-soft") errorMinusSoft("error-soft"),
        @Json(name = "error-hard") errorMinusHard("error-hard");
    }

}

