/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.FallbackOperationError
import com.corbado.api.models.PasskeyOperation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param session 
 * @param signedPasskeyData 
 * @param passkeyOperation 
 * @param fallbackOperationError 
 */


data class ConnectLoginFinishRsp (

    @Json(name = "session")
    val session: kotlin.String,

    @Json(name = "signedPasskeyData")
    val signedPasskeyData: kotlin.String,

    @Json(name = "passkeyOperation")
    val passkeyOperation: PasskeyOperation? = null,

    @Json(name = "fallbackOperationError")
    val fallbackOperationError: FallbackOperationError? = null

) {


}

