/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isConditionalUI 
 * @param assertionResponse 
 * @param loadedMs 
 */


data class ConnectLoginFinishReq (

    @Json(name = "isConditionalUI")
    val isConditionalUI: kotlin.Boolean,

    @Json(name = "assertionResponse")
    val assertionResponse: kotlin.String,

    @Json(name = "loadedMs")
    val loadedMs: kotlin.Long? = null

) {


}

