/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.ClientInformation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientInformation 
 * @param flags 
 * @param invitationToken 
 */


data class ConnectAppendInitReq (

    @Json(name = "clientInformation")
    val clientInformation: ClientInformation,

    @Json(name = "flags")
    val flags: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "invitationToken")
    val invitationToken: kotlin.String? = null

) {


}

