/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appendTokenValue 
 * @param loadedMs 
 * @param forcePasskeyAppend 
 */


data class ConnectAppendStartReq (

    @Json(name = "appendTokenValue")
    val appendTokenValue: kotlin.String,

    @Json(name = "loadedMs")
    val loadedMs: kotlin.Long,

    @Json(name = "forcePasskeyAppend")
    val forcePasskeyAppend: kotlin.Boolean? = null

) {


}

