/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.PasskeyEventType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventType 
 * @param message 
 * @param challenge 
 */


data class ConnectEventCreateReq (

    @Json(name = "eventType")
    val eventType: PasskeyEventType,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "challenge")
    val challenge: kotlin.String? = null

) {


}

