/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.FallbackOperationError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param assertionOptions 
 * @param isCDA 
 * @param fallbackOperationError 
 * @param preferImmediatelyAvailable 
 */


data class ConnectLoginStartRsp (

    @Json(name = "assertionOptions")
    val assertionOptions: kotlin.String,

    @Json(name = "isCDA")
    val isCDA: kotlin.Boolean,

    @Json(name = "fallbackOperationError")
    val fallbackOperationError: FallbackOperationError,

    @Json(name = "preferImmediatelyAvailable")
    val preferImmediatelyAvailable: kotlin.Boolean? = null

) {


}

