/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param connectToken 
 * @param credentialID 
 */


data class ConnectManageDeleteReq (

    @Json(name = "connectToken")
    val connectToken: kotlin.String,

    @Json(name = "credentialID")
    val credentialID: kotlin.String

) {


}

