/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.Passkey

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param passkeys 
 * @param rpID 
 * @param userID 
 */


data class ConnectManageListRsp (

    @Json(name = "passkeys")
    val passkeys: kotlin.collections.List<Passkey>,

    @Json(name = "rpID")
    val rpID: kotlin.String,

    @Json(name = "userID")
    val userID: kotlin.String

) {


}

