/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param processID 
 * @param expiresAt 
 * @param frontendApiUrl 
 * @param manageAllowed 
 * @param flags 
 * @param newClientEnvHandle 
 */


data class ConnectManageInitRsp (

    @Json(name = "processID")
    val processID: kotlin.String,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.Int,

    @Json(name = "frontendApiUrl")
    val frontendApiUrl: kotlin.String,

    @Json(name = "manageAllowed")
    val manageAllowed: kotlin.Boolean,

    @Json(name = "flags")
    val flags: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "newClientEnvHandle")
    val newClientEnvHandle: kotlin.String? = null

) {


}

