/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reason 
 */


data class ContinueOnOtherDevice (

    @Json(name = "reason")
    val reason: ContinueOnOtherDevice.Reason

) {

    /**
     * 
     *
     * Values: emailMinusLinkMinusVerified,processMinusAlreadyMinusCompleted
     */
    @JsonClass(generateAdapter = false)
    enum class Reason(val value: kotlin.String) {
        @Json(name = "email-link-verified") emailMinusLinkMinusVerified("email-link-verified"),
        @Json(name = "process-already-completed") processMinusAlreadyMinusCompleted("process-already-completed");
    }

}

