/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.RequestError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param initFallback 
 * @param identifier 
 * @param error 
 */


data class FallbackOperationError (

    @Json(name = "initFallback")
    val initFallback: kotlin.Boolean,

    @Json(name = "identifier")
    val identifier: kotlin.String? = null,

    @Json(name = "error")
    val error: RequestError? = null

) {


}

