/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.PasskeyOperation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param shortSession 
 * @param sessionToken 
 * @param longSession This is only set if the project environment is set to 'dev'. If set the UI components will set the longSession in local storage because the cookie dropping will not work in Safari for example (\"third-party cookie\").
 * @param refreshToken This is only set if the project environment is set to 'dev'. If set the UI components will set the longSession in local storage because the cookie dropping will not work in Safari for example (\"third-party cookie\").
 * @param passkeyOperation 
 */


data class GeneralBlockCompleted (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "shortSession")
    @Deprecated(message = "This property is deprecated.")
    val shortSession: kotlin.String,

    @Json(name = "sessionToken")
    val sessionToken: kotlin.String,

    /* This is only set if the project environment is set to 'dev'. If set the UI components will set the longSession in local storage because the cookie dropping will not work in Safari for example (\"third-party cookie\"). */
    @Json(name = "longSession")
    @Deprecated(message = "This property is deprecated.")
    val longSession: kotlin.String? = null,

    /* This is only set if the project environment is set to 'dev'. If set the UI components will set the longSession in local storage because the cookie dropping will not work in Safari for example (\"third-party cookie\"). */
    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "passkeyOperation")
    val passkeyOperation: PasskeyOperation? = null

) {


}

