/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.GeneralBlockVerifyIdentifierAlternativeVerificationMethodsInner
import com.corbado.api.models.RequestError
import com.corbado.api.models.VerificationMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param verificationMethod 
 * @param identifier 
 * @param alternativeVerificationMethods 
 * @param isPostLoginVerification 
 * @param retryNotBefore 
 * @param error 
 */


data class GeneralBlockVerifyIdentifier (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "verificationMethod")
    val verificationMethod: VerificationMethod,

    @Json(name = "identifier")
    val identifier: kotlin.String,

    @Json(name = "alternativeVerificationMethods")
    val alternativeVerificationMethods: kotlin.collections.List<GeneralBlockVerifyIdentifierAlternativeVerificationMethodsInner>,

    @Json(name = "isPostLoginVerification")
    val isPostLoginVerification: kotlin.Boolean,

    @Json(name = "retryNotBefore")
    val retryNotBefore: kotlin.Int? = null,

    @Json(name = "error")
    val error: RequestError? = null

) {


}

