/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.VerificationMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param verificationMethod 
 * @param identifier 
 */


data class GeneralBlockVerifyIdentifierAlternativeVerificationMethodsInner (

    @Json(name = "verificationMethod")
    val verificationMethod: VerificationMethod,

    @Json(name = "identifier")
    val identifier: kotlin.String

) {


}

