/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.RequestError
import com.corbado.api.models.SocialData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param identifierValue 
 * @param isPhone 
 * @param isPhoneAvailable 
 * @param isEmailAvailable 
 * @param isUsernameAvailable 
 * @param socialData 
 * @param conditionalUIChallenge 
 * @param fieldError 
 * @param error 
 */


data class GeneralBlockLoginInit (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "isPhone")
    val isPhone: kotlin.Boolean,

    @Json(name = "isPhoneAvailable")
    val isPhoneAvailable: kotlin.Boolean,

    @Json(name = "isEmailAvailable")
    val isEmailAvailable: kotlin.Boolean,

    @Json(name = "isUsernameAvailable")
    val isUsernameAvailable: kotlin.Boolean,

    @Json(name = "socialData")
    val socialData: SocialData,

    @Json(name = "conditionalUIChallenge")
    val conditionalUIChallenge: kotlin.String? = null,

    @Json(name = "fieldError")
    val fieldError: RequestError? = null,

    @Json(name = "error")
    val error: RequestError? = null

) {


}

