/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param challenge 
 * @param identifierValue 
 * @param loginHint 
 */


data class GeneralBlockPasskeyVerify (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "challenge")
    val challenge: kotlin.String,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "loginHint")
    val loginHint: GeneralBlockPasskeyVerify.LoginHint? = null

) {

    /**
     * 
     *
     * Values: cda
     */
    @JsonClass(generateAdapter = false)
    enum class LoginHint(val value: kotlin.String) {
        @Json(name = "cda") cda("cda");
    }

}

