/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.FullNameWithError
import com.corbado.api.models.LoginIdentifierWithError
import com.corbado.api.models.RequestError
import com.corbado.api.models.SocialData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param identifiers 
 * @param fullName 
 * @param socialData 
 * @param error 
 */


data class GeneralBlockSignupInit (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<LoginIdentifierWithError>,

    @Json(name = "fullName")
    val fullName: FullNameWithError? = null,

    @Json(name = "socialData")
    val socialData: SocialData? = null,

    @Json(name = "error")
    val error: RequestError? = null

) {


}

