/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.RequestData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param httpStatusCode HTTP status code of operation
 * @param message 
 * @param requestData 
 * @param runtime Runtime in seconds for this request
 */


data class GenericRsp (

    /* HTTP status code of operation */
    @Json(name = "httpStatusCode")
    val httpStatusCode: kotlin.Int,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "requestData")
    val requestData: RequestData,

    /* Runtime in seconds for this request */
    @Json(name = "runtime")
    val runtime: kotlin.Float

) {


}

