/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierType
import com.corbado.api.models.PasskeyIconSet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockType 
 * @param challenge 
 * @param identifierValue 
 * @param identifierType 
 * @param autoSubmit 
 * @param passkeyIconSet 
 * @param variant 
 */


data class GeneralBlockPasskeyAppend (

    @Json(name = "blockType")
    val blockType: kotlin.String,

    @Json(name = "challenge")
    val challenge: kotlin.String,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "identifierType")
    val identifierType: LoginIdentifierType,

    @Json(name = "autoSubmit")
    val autoSubmit: kotlin.Boolean,

    @Json(name = "passkeyIconSet")
    val passkeyIconSet: PasskeyIconSet,

    @Json(name = "variant")
    val variant: GeneralBlockPasskeyAppend.Variant

) {

    /**
     * 
     *
     * Values: default,afterMinusHybrid,afterMinusError
     */
    @JsonClass(generateAdapter = false)
    enum class Variant(val value: kotlin.String) {
        @Json(name = "default") default("default"),
        @Json(name = "after-hybrid") afterMinusHybrid("after-hybrid"),
        @Json(name = "after-error") afterMinusError("after-error");
    }

}

