/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identifierType 
 * @param `value` 
 */


data class IdentifierUpdateReq (

    @Json(name = "identifierType")
    val identifierType: LoginIdentifierType,

    @Json(name = "value")
    val `value`: kotlin.String

) {


}

