/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierType
import com.corbado.api.models.VerificationMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * tbd.
 *
 * @param identifierType 
 * @param verificationType 
 */


data class IdentifierVerifyStartReq (

    @Json(name = "identifierType")
    val identifierType: LoginIdentifierType,

    @Json(name = "verificationType")
    val verificationType: VerificationMethod

) {


}

