/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param `value` 
 * @param type 
 * @param status 
 */


data class Identifier (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.String,

    @Json(name = "type")
    val type: LoginIdentifierType,

    @Json(name = "status")
    val status: kotlin.String

) {


}

