/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param platform 
 * @param platformVersion 
 * @param mobile 
 */


data class JavaScriptHighEntropy (

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "platformVersion")
    val platformVersion: kotlin.String,

    @Json(name = "mobile")
    val mobile: kotlin.Boolean

) {


}

