/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierType
import com.corbado.api.models.RequestError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param identifier 
 * @param error 
 */


data class LoginIdentifierWithError (

    @Json(name = "type")
    val type: LoginIdentifierType,

    @Json(name = "identifier")
    val identifier: kotlin.String,

    @Json(name = "error")
    val error: RequestError? = null

) {


}

