/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.Paging
import com.corbado.api.models.Passkey

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param passkeys 
 * @param paging 
 */


data class MePasskeyRsp (

    @Json(name = "passkeys")
    val passkeys: kotlin.collections.List<Passkey>,

    @Json(name = "paging")
    val paging: Paging

) {


}

