/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param attestationOptions 
 * @param newClientEnvHandle 
 * @param appendNotAllowedReason 
 */


data class MePasskeysAppendStartRsp (

    @Json(name = "attestationOptions")
    val attestationOptions: kotlin.String,

    @Json(name = "newClientEnvHandle")
    val newClientEnvHandle: kotlin.String? = null,

    @Json(name = "appendNotAllowedReason")
    val appendNotAllowedReason: MePasskeysAppendStartRsp.AppendNotAllowedReason? = null

) {

    /**
     * 
     *
     * Values: passkey_already_exists,passkeys_not_supported
     */
    @JsonClass(generateAdapter = false)
    enum class AppendNotAllowedReason(val value: kotlin.String) {
        @Json(name = "passkey_already_exists") passkey_already_exists("passkey_already_exists"),
        @Json(name = "passkeys_not_supported") passkeys_not_supported("passkeys_not_supported");
    }

}

