/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param shortSession 
 * @param sessionToken 
 */


data class MeRefreshRsp (

    @Json(name = "shortSession")
    @Deprecated(message = "This property is deprecated.")
    val shortSession: kotlin.String,

    @Json(name = "sessionToken")
    val sessionToken: kotlin.String

) {


}

