/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.Identifier
import com.corbado.api.models.SocialAccount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param fullName 
 * @param identifiers 
 * @param socialAccounts 
 */


data class MeRsp (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "fullName")
    val fullName: kotlin.String,

    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<Identifier>,

    @Json(name = "socialAccounts")
    val socialAccounts: kotlin.collections.List<SocialAccount>

) {


}

