/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param platform 
 * @param platformVersion 
 * @param name 
 * @param version 
 * @param build 
 * @param deviceOwnerAuth 
 * @param isBluetoothAvailable 
 * @param isBluetoothOn 
 * @param isGooglePlayServices 
 * @param isDeviceSecure 
 * @param error 
 */


data class NativeMeta (

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "platformVersion")
    val platformVersion: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "build")
    val build: kotlin.String? = null,

    @Json(name = "deviceOwnerAuth")
    val deviceOwnerAuth: NativeMeta.DeviceOwnerAuth? = null,

    @Json(name = "isBluetoothAvailable")
    val isBluetoothAvailable: kotlin.Boolean? = null,

    @Json(name = "isBluetoothOn")
    val isBluetoothOn: kotlin.Boolean? = null,

    @Json(name = "isGooglePlayServices")
    val isGooglePlayServices: kotlin.Boolean? = null,

    @Json(name = "isDeviceSecure")
    val isDeviceSecure: kotlin.Boolean? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: none,code,biometrics
     */
    @JsonClass(generateAdapter = false)
    enum class DeviceOwnerAuth(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "code") code("code"),
        @Json(name = "biometrics") biometrics("biometrics");
    }

}

