/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page current page returned in response
 * @param totalPages total number of pages available
 * @param totalItems total number of items available
 */


data class Paging (

    /* current page returned in response */
    @Json(name = "page")
    val page: kotlin.Int = 1,

    /* total number of pages available */
    @Json(name = "totalPages")
    val totalPages: kotlin.Int,

    /* total number of items available */
    @Json(name = "totalItems")
    val totalItems: kotlin.Int

) {


}

