/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * tbd.
 *
 * @param signedChallenge 
 */


data class PasskeyMediationFinishReq (

    @Json(name = "signedChallenge")
    val signedChallenge: kotlin.String

) {


}

