/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.AaguidDetails
import com.corbado.api.models.LoginIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param operationType 
 * @param identifierValue 
 * @param identifierType 
 * @param ceremonyType 
 * @param aaguidDetails 
 */


data class PasskeyOperation (

    @Json(name = "operationType")
    val operationType: PasskeyOperation.OperationType,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "identifierType")
    val identifierType: LoginIdentifierType,

    @Json(name = "ceremonyType")
    val ceremonyType: PasskeyOperation.CeremonyType,

    @Json(name = "aaguidDetails")
    val aaguidDetails: AaguidDetails? = null

) {

    /**
     * 
     *
     * Values: append,verify
     */
    @JsonClass(generateAdapter = false)
    enum class OperationType(val value: kotlin.String) {
        @Json(name = "append") append("append"),
        @Json(name = "verify") verify("verify");
    }
    /**
     * 
     *
     * Values: local,cda,securityMinusKey
     */
    @JsonClass(generateAdapter = false)
    enum class CeremonyType(val value: kotlin.String) {
        @Json(name = "local") local("local"),
        @Json(name = "cda") cda("cda"),
        @Json(name = "security-key") securityMinusKey("security-key");
    }

}

