/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.BlockType
import com.corbado.api.models.ClientInformation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * tbd.
 *
 * @param clientInformation 
 * @param passkeyAppendShown 
 * @param optOutOfPasskeyAppendAfterHybrid deprecated
 * @param preferredBlock 
 */


data class ProcessInitReq (

    @Json(name = "clientInformation")
    val clientInformation: ClientInformation,

    @Json(name = "passkeyAppendShown")
    val passkeyAppendShown: kotlin.Long? = null,

    /* deprecated */
    @Json(name = "optOutOfPasskeyAppendAfterHybrid")
    val optOutOfPasskeyAppendAfterHybrid: kotlin.Boolean? = null,

    @Json(name = "preferredBlock")
    val preferredBlock: BlockType? = null

) {


}

