/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appName 
 * @param frontendApiUrl 
 * @param hideBadge 
 */


data class ProcessCommon (

    @Json(name = "appName")
    val appName: kotlin.String,

    @Json(name = "frontendApiUrl")
    val frontendApiUrl: kotlin.String,

    @Json(name = "hideBadge")
    val hideBadge: kotlin.Boolean

) {


}

