/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param expiresAt 
 */


data class ProcessStaticInfo (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.Int

) {


}

