/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.ProcessResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * tbd.
 *
 * @param token 
 * @param expiresAt 
 * @param processResponse 
 * @param newClientEnvHandle 
 */


data class ProcessInitRsp (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.Int,

    @Json(name = "processResponse")
    val processResponse: ProcessResponse,

    @Json(name = "newClientEnvHandle")
    val newClientEnvHandle: kotlin.String? = null

) {


}

