/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.BlockBody
import com.corbado.api.models.ProcessCommon
import com.corbado.api.models.ProcessStaticInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockBody 
 * @param common 
 * @param newProcess 
 */


data class ProcessResponse (

    @Json(name = "blockBody")
    val blockBody: BlockBody,

    @Json(name = "common")
    val common: ProcessCommon,

    @Json(name = "newProcess")
    val newProcess: ProcessStaticInfo? = null

) {


}

