/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Data about the request itself, can be used for debugging
 *
 * @param requestID Unique ID of request, you can provide your own while making the request, if not the ID will be randomly generated on server side
 * @param link Link to dashboard with details about request
 */


data class RequestData (

    /* Unique ID of request, you can provide your own while making the request, if not the ID will be randomly generated on server side */
    @Json(name = "requestID")
    val requestID: kotlin.String,

    /* Link to dashboard with details about request */
    @Json(name = "link")
    val link: kotlin.String

) {


}

