/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.SessionTokenCookieConfig
import com.corbado.api.models.ShortSessionCookieConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param useSessionManagement 
 * @param shortSessionCookieConfig 
 * @param sessionTokenCookieConfig 
 * @param frontendApiUrl 
 */


data class SessionConfigRsp (

    @Json(name = "useSessionManagement")
    val useSessionManagement: kotlin.Boolean,

    @Json(name = "shortSessionCookieConfig")
    @Deprecated(message = "This property is deprecated.")
    val shortSessionCookieConfig: ShortSessionCookieConfig? = null,

    @Json(name = "sessionTokenCookieConfig")
    val sessionTokenCookieConfig: SessionTokenCookieConfig? = null,

    @Json(name = "frontendApiUrl")
    val frontendApiUrl: kotlin.String? = null

) {


}

