/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param domain 
 * @param secure 
 * @param sameSite 
 * @param path 
 * @param lifetimeSeconds 
 */

@Deprecated(message = "This schema is deprecated.")

data class ShortSessionCookieConfig (

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "secure")
    val secure: kotlin.Boolean,

    @Json(name = "sameSite")
    val sameSite: ShortSessionCookieConfig.SameSite,

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "lifetimeSeconds")
    val lifetimeSeconds: kotlin.Int

) {

    /**
     * 
     *
     * Values: lax,strict,none
     */
    @JsonClass(generateAdapter = false)
    enum class SameSite(val value: kotlin.String) {
        @Json(name = "lax") lax("lax"),
        @Json(name = "strict") strict("strict"),
        @Json(name = "none") none("none");
    }

}

