/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * tbd.
 *
 * @param identifiers 
 * @param fullName 
 */


data class SignupInitReq (

    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<LoginIdentifier>,

    @Json(name = "fullName")
    val fullName: kotlin.String? = null

) {


}

