/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.SocialProviderType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param providerType 
 * @param identifierValue 
 * @param avatarUrl 
 * @param fullName 
 */


data class SocialAccount (

    @Json(name = "providerType")
    val providerType: SocialProviderType,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "avatarUrl")
    val avatarUrl: kotlin.String,

    @Json(name = "fullName")
    val fullName: kotlin.String

) {


}

