/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.RequestError
import com.corbado.api.models.SocialProviderType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param providers 
 * @param status 
 * @param oauthUrl 
 * @param error 
 */


data class SocialData (

    @Json(name = "providers")
    val providers: kotlin.collections.List<SocialProviderType>,

    @Json(name = "status")
    val status: SocialData.Status,

    @Json(name = "oauthUrl")
    val oauthUrl: kotlin.String? = null,

    @Json(name = "error")
    val error: RequestError? = null

) {

    /**
     * 
     *
     * Values: initial,started,finished
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "initial") initial("initial"),
        @Json(name = "started") started("started"),
        @Json(name = "finished") finished("finished");
    }

}

