/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.AuthType
import com.corbado.api.models.SocialProviderType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param providerType 
 * @param redirectUrl 
 * @param authType 
 */


data class SocialVerifyStartReq (

    @Json(name = "providerType")
    val providerType: SocialProviderType,

    @Json(name = "redirectUrl")
    val redirectUrl: kotlin.String,

    @Json(name = "authType")
    val authType: AuthType

) {


}

