/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models

import com.corbado.api.models.LoginIdentifierConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fullNameRequired 
 * @param identifiers 
 */


data class UserDetailsConfigRsp (

    @Json(name = "fullNameRequired")
    val fullNameRequired: kotlin.Boolean,

    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<LoginIdentifierConfig>

) {


}

