/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.corbado.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: emailMinusLink,emailMinusOtp,phoneMinusOtp
 */

@JsonClass(generateAdapter = false)
enum class VerificationMethod(val value: kotlin.String) {

    @Json(name = "email-link")
    emailMinusLink("email-link"),

    @Json(name = "email-otp")
    emailMinusOtp("email-otp"),

    @Json(name = "phone-otp")
    phoneMinusOtp("phone-otp");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VerificationMethod) "$data" else null

        /**
         * Returns a valid [VerificationMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VerificationMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

